Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build5979983429863903334">Bundle Update as a Service - Tachikoma.io</a>

Exec tachikoma update 20150307143925

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build5985056942590691108">Bundle Update as a Service - Tachikoma.io</a>

Exec tachikoma update 20150321143945

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build5987593700056019198">Bundle Update as a Service - Tachikoma.io</a>

Exec tachikoma update 20150328143916

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build5990130463749836588">Bundle Update as a Service - Tachikoma.io</a>

Exec tachikoma update 20150404144008

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build5992666238909796127">Bundle Update as a Service - Tachikoma.io</a>

Exec tachikoma update 20150411143619

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build5995202959771876424">Bundle Update as a Service - Tachikoma.io</a>

Exec tachikoma update 20150418143622

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build5997739676472067254">Bundle Update as a Service - Tachikoma.io</a>

Exec tachikoma update 20150425143625

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6015496673683247183">Bundle Update as a Service - Tachikoma.io</a>

Exec tachikoma update 20150613143622

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6026018167193282819">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6026018167193282819">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20150712152506

---

lib/circleci/bundle/update/pr.rb

> Our final big feature is support for locking Ruby versions!
c.f. [Bundler: The new index format, Fastly, and Bundler 1.12](http://bundler.io/blog/2016/04/28/the-new-index-format-fastly-and-bundler-1-12.html)

bundle update --ruby

---

Gemfile.lock

Bump up compare_linker
See https://github.com/masutaka/compare_linker/releases/tag/v1.3.0

Bundle update 2016-10-09

---

Gemfile.lock

bundle update at 2017-05-26 19:02:13 JST

---

Gemfile.lock

bundle update at 2017-06-02 19:01:51 JST

---

Gemfile.lock

bundle update at 2017-07-21 19:00:35 JST

---

Gemfile.lock

bundle update at 2017-07-28 19:01:06 JST

---

Gemfile.lock

bundle update at 2017-08-25 23:21:42 JST

---

Gemfile.lock

bundle update at 2017-09-15 19:01:18 JST

---

Gemfile.lock

bundle update at 2017-10-27 19:01:05 JST

---

Gemfile.lock

bundle update at 2017-11-03 19:00:20 JST

---

Gemfile.lock

bundle update at 2017-11-10 19:00:20 JST

---

Gemfile.lock

bundle update at 2017-11-17 19:00:59 JST

---

Gemfile.lock

bundle update at 2017-12-22 19:00:19 JST

---

Gemfile.lock

bundle update at 2018-01-26 19:00:20 JST

---

Gemfile.lock

bundle update at 2018-02-16 19:00:19 JST

---

Gemfile.lock

bundle update at 2018-03-23 19:00:23 JST

---

Gemfile.lock

bundle update at 2018-05-25 19:00:21 JST

---

bin/circleci-bundle-update-pr
lib/circleci/bundle/update/pr.rb

I'd like to assign someone. So I added assignees option.
octkit references is followings:
https://octokit.github.io/octokit.rb/Octokit/Client/Issues.html#add_assignees-instance_method

added --assignees option

---

Gemfile.lock

bundle update at 2018-08-31 19:00:19 JST

---

Gemfile.lock

bundle update at 2018-09-21 19:00:25 JST

---

lib/circleci/bundle/update/pr.rb

Don't create PR if it exists

---

README.md
lib/circleci/bundle/update/pr.rb
lib/circleci/bundle/update/pr/note.rb
spec/circleci/bundle/update/pr/note_spec.rb

User can customize PR description

---

Gemfile.lock

bundle update at 2018-11-30 19:00:22 JST

---

Gemfile.lock

bundle update at 2018-12-07 19:00:18 JST

---

Gemfile.lock

bundle update at 2019-03-08 19:00:18 JST

---

Gemfile.lock

bundle update at 2019-04-05 19:00:51 JST

---

.circleci/config.yml

closes #70
Add the following ruby versions to CI in addition to Ruby-2.2.
* Ruby-2.3
* Ruby-2.4
* Ruby-2.5
* Ruby-2.6

CI multi ruby versions

---

Gemfile.lock

bundle update at 2019-04-26 19:00:22 JST

---

Gemfile.lock

bundle update at 2019-05-10 19:00:38 JST

---

.gitignore
lib/circleci/bundle/update/pr.rb
spec/circleci/bundle/update/pr_spec.rb

refs https://github.com/masutaka/circleci-bundle-update-pr/issues/100

Use lockfile path for commit

---

lib/circleci/bundle/update/pr.rb
spec/circleci/bundle/update/pr_spec.rb

fixes https://github.com/masutaka/circleci-bundle-update-pr/issues/104

Fix gemlock path for relative path in CIRCLE_WORKING_DIRECTORY

---

Gemfile.lock

bundle update at 2020-02-18 19:00:23 JST

---

Gemfile.lock

bundle update at 2020-08-25 19:00:54 JST

---

Gemfile.lock

bundle update at 2020-09-08 19:01:09 JST

---

Gemfile.lock

bundle update at 2021-01-12 19:01:14 JST

---

Gemfile.lock

bundle update at 2021-01-19 19:01:15 JST

---

Gemfile.lock

bundle update at 2021-01-26 19:01:18 JST

---

Gemfile.lock

bundle update at 2021-02-23 19:01:07 JST

---

Gemfile.lock

bundle update at 2021-04-01 19:01:05 JST

---

Gemfile.lock

bundle update at 2021-11-01 19:03:13 JST

---

Gemfile.lock
lib/circleci/bundle/update/pr.rb
spec/circleci/bundle/update/pr_spec.rb

bundle update at 2022-05-01 19:03:05 JST

---

Gemfile.lock

bundle update at 2023-09-01 19:03:07 JST

---

Gemfile.lock

bundle update at 2023-12-01 19:10:43 JST

---

.circleci/config.yml

https://www.ruby-lang.org/en/news/2023/12/25/ruby-3-3-0-released/

Support Ruby 3.3

---

Gemfile.lock

bundle update at 2024-01-01 19:10:55 JST

---

.circleci/config.yml
Gemfile.lock

bundle update at 2024-02-01 19:10:52 JST

---

Gemfile.lock

bundle update at 2024-06-01 19:10:44 JST

---

Gemfile.lock

bundle update at 2024-08-01 19:10:58 JST

---

README.md

This PR will adjust https://github.com/masutaka/circleci-bundle-update-pr/pull/179

Adjust FOSSA badge

---

README.md

Remove license from README.md

---

Gemfile.lock
lib/circleci/bundle/update/pr/version.rb

https://github.com/masutaka/circleci-bundle-update-pr/compare/v5.0.5...fedbf2d99a2c7eb506cfb9110d91f0d33d22d6e5

Release for v5.0.6

---

Gemfile.lock
lib/circleci/bundle/update/pr/version.rb

https://github.com/masutaka/circleci-bundle-update-pr/compare/v5.0.6...64ce099efbd7d838eceb134ea7a37a8ba2d0686a

Release for v5.0.7

---

Gemfile.lock
lib/circleci/bundle/update/pr/version.rb

https://github.com/masutaka/circleci-bundle-update-pr/compare/v5.0.7...486cf64a2d1d1482cc96ea2ed1e0ca94cb6a307b

Release for v5.0.8

---

Gemfile.lock
lib/circleci/bundle/update/pr/version.rb

https://github.com/masutaka/circleci-bundle-update-pr/compare/v5.0.8...6eb6317756b5daf369d3bf6aca7168ec890b52c0

Release for v5.0.9

---

Gemfile.lock
lib/circleci/bundle/update/pr/version.rb

https://github.com/masutaka/circleci-bundle-update-pr/compare/v5.0.9...210edb3530d27d3285fc515dd1f26f8be40d1d01

Release for v5.0.10

---

Gemfile.lock

in https://github.com/masutaka/circleci-bundle-update-pr/pull/195

Forgot to run `$ bundle`

---

Gemfile.lock
lib/circleci/bundle/update/pr/version.rb

https://github.com/masutaka/circleci-bundle-update-pr/compare/v5.0.10...d1ad91028c7cd482ee93fadf62bbfd6438ef3afe

Release for v5.1.0

---

Gemfile.lock

bundle update at 2025-02-01 19:11:06 JST

---

Gemfile.lock
lib/circleci/bundle/update/pr/version.rb

https://github.com/masutaka/circleci-bundle-update-pr/compare/v5.1.0...794553861dbd65d1e3596278da1bbccded64dc76

Release for v5.1.1

---

Gemfile.lock
lib/circleci/bundle/update/pr/version.rb

https://github.com/masutaka/circleci-bundle-update-pr/compare/v5.1.1...b5c5e068d68e72af0de4a1e54304cd25f2176c50

Release for v5.1.2

---

Gemfile.lock
lib/circleci/bundle/update/pr/version.rb

https://github.com/masutaka/circleci-bundle-update-pr/compare/v5.1.2...1959007dca68848d46c2d5da5737f7bf67f548b5

Release for v5.1.3

---

Gemfile.lock
lib/circleci/bundle/update/pr/version.rb

https://github.com/masutaka/circleci-bundle-update-pr/compare/v5.1.5...565ac94d453eb5356007c87900138c402e3f2693

Release for v5.1.6
