- lib/circleci/bundle/update/pr.rb
gemを取得できず `bundle update` の際にエラーが起きた場合でも、常に `circleci-bundle-update-pr` コマンドが正常終了してしまうため、`bundle update`に失敗した場合と、gemのupdateが全くない場合との区別が付きにくいという問題がありました。
※ 画像はイメージです
`bundle update` が失敗した場合は、`RuntimeError` で exit(1) されるようにして、CiecleCI上で `bundle update` が失敗したことが分かるようにしました。
> Raise RuntimeError to exit(1) on bundle update failure

- README.md
Since there is not an instruction for using circleci-bundle-update-pr on this repository itself, I have added the detailed instruction document to readme.
It is kind like the document of the following 3 instructions with mixed (and yes, translated into English):
- https://masutaka.net/chalow/2015-07-28-1.html
- http://ppworks.hatenablog.jp/entry/2015/12/23/214644
- http://qiita.com/yuku_t/items/0f8e48771822420d3ffa (for triggering builds via curl)
How does this sound to you? 😄
> Add detailed instruction document to readme

- lib/circleci/bundle/update/pr.rb
I have added personal access token (OAuth token) to remote branch endpoint URL which is used for pushing bundle-updated branch to GitHub.
For the moment, to push a branch from CircleCI to GitHub, circleci-bundle-update-pr implicitly uses SSH key configured on CircleCI.
This means you have to configure SSH key with appropriate GitHub access right otherwise pushing to GiHub will fail.
However, maybe you don't want to add extra SSH keys to CircleCI, because you already have a personal access token with "repo" scope as `GITHUB_ACCESS_TOKEN` environment variable, which can also be used for pushing.
Although I'm not exactly sure if embedding a token in URL has scurity risk, I think in most cases using OAuth token with correctly limited scope rather than full access personal SSH key is reduce …
> GitHub push using personal access token instead of SSH key on CircleCI

- lib/circleci/bundle/update/pr.rb
This PR fixes github_host method of Circleci:: Bundle::Update::Pr module.
`$1 if 'https://github.com/masutaka/circleci-bundle-update-pr.git' =~ %r{([^@]+?):}` return 'https'
I think that is solved by moving "`https://github.com check`" before "`git@github.com check`".
> Fix github_host of Pr module

- README.md
- bin/circleci-bundle-update-pr
- lib/circleci/bundle/update/pr.rb
PR has not been maked if it has already exists In the previous update.
However, I need newer one when I miss merge.
Making new update PR by myself is too much hassle and Wating next cron iteration feel so far!
So I want to add the option allow users to make duplicate bundle update PR.
* Confirmed to make duplicate PR with `-d` option.
* Confirmed not to make duplicate PR without `-d` option.
> [new option]make pr even if it has already exists

- lib/circleci/bundle/update/pr.rb
Specifying a username with white spaces in `$ circleci-bundle-update-pr <git username>` will result in unintended settings.
**Expect**
```
$ circleci-bundle-update-pr 'hoge fuga' example@example.com
...
$ git config user.name
hoge fuga
```
**Actual**
```
$ circleci-bundle-update-pr 'hoge fuga' example@example.com
...
$ git config user.name
hoge
```
**Expect**
```
$ circleci-bundle-update-pr 'hoge fuga piyo' example@example.com
...
$ git config user.name
hoge fuga piyo
```
**Actual**
```
$ circleci-bundle-update-pr 'hoge fuga piyo' example@example.com
...
$ git config user.name
```
And `circleci-bundle-update-pr` occurs error.
Clock [here](https://circleci.com/gh/feedforce/feedforce-ruboty/10) for more detail.
* Around `#{git_username}` by single quotes
Try manual unit tests.
```
$ irb …
```
> Allow white spaces in Git user.name

- lib/circleci/bundle/update/pr.rb
It's convenient to change `BRANCH_PREFIX` to any string.
> set BRANCH_PREFIX from ENV

- lib/circleci/bundle/update/pr.rb
- spec/circleci/bundle/update/pr_spec.rb
This PR changes a message displayed if running branch is not included in target branches.
For example, ciecleci-bundle-update-pr is run on `develop` branch with no args (this means target branche is only `master`.) ciecleci-bundle-update-pr says 
```
No changes due to bundle update
```
This message doesn't contain any information about the reason.
So, this PR changes the message by
```
Skip because CIRCLE_BRANCH[develop] is not included in target branches[master].
```
> Display another message if running branch is not included in target branches.

- .circleci/config.yml
- .rubocop.yml
- .rubocop_todo.yml
- lib/circleci/bundle/update/pr.rb
- lib/circleci/bundle/update/pr/version.rb
Drop unsupported ruby-2.2.
It is hard to support ruby-2.2 while fixing FrozenError.
Also I might drop ruby-2.3 soon.
https://www.ruby-lang.org/en/downloads/
> Drop ruby-2.2

- lib/circleci/bundle/update/pr.rb
Suppose a project where more than one Gemfile exist in subdirectories.
Running `circleci-bundle-update-pr` within each directory(`workdir`) of these Gemfiles will create PRs with same title prefix which are difficult to distinguish from each other.  `BRANCH_PREFIX` does not help in this case because it won't appear in titles.
With configurable title prefix, `circleci-bundle-update-pr` of each directory can generate distinguishable PRs.
> Make TITLE_PREFIX injectable from environment

- README.md
- lib/circleci/bundle/update/pr.rb
I replaced system git operation (e.g. `git commit`) with GitHub API.
`circleci-bundle-update-pr` is implicitly dependent on system `git`.
https://github.com/masutaka/circleci-bundle-update-pr/blob/v1.16.1/lib/circleci/bundle/update/pr.rb#L105-L111
So I want to remove this implicitly dependent.
I want to run `circleci-bundle-update-pr` on GitHub Actions.
`secrets.GITHUB_TOKEN`  (default token on GitHub Actions) has given permission to GitHub API , but hasn't given permission to syetem `git push`.
https://help.github.com/en/articles/virtual-environments-for-github-actions#github_token-secret
So I replaced system git operation to GitHub API operation.
> git operation without system git command

- README.md
* Use  `GITHUB_REF` (defined in GitHub Actions) instead of `GITHUB_BRANCH `
* `GITHUB_REPOSITORY` is defined in GitHub Actions. So I removed.
c.f. https://help.github.com/en/articles/virtual-environments-for-github-actions#default-environment-variables
> Tweak doc for GitHub Actions

- README.md
- bin/circleci-bundle-update-pr
- lib/circleci/bundle/update/pr.rb
Currently the default GitHub branch is `main`
c.f. https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/
> Add main branch to default branch

- .circleci/config.yml
- README.md
I changed the default branch of this repository from `master` to `main` because the number of repositories on the main branch has been increasing around me.
> Change default branch from `master` to `main`

- Gemfile.lock
> bundle update at 2024-05-01 19:10:44 JST

- Gemfile.lock
> bundle update at 2024-07-01 19:11:03 JST

- Gemfile.lock
> bundle update at 2024-12-01 19:11:02 JST

- .circleci/config.yml
- circleci-bundle-update-pr.gemspec
https://www.ruby-lang.org/en/news/2024/12/25/ruby-3-4-0-released/
https://www.ruby-lang.org/en/news/2024/12/25/ruby-3-4-1-released/
> Support Ruby 3.4 and set to the default

- Gemfile.lock
> bundle update at 2025-03-01 19:11:15 JST

- .rubocop.yml
```console
$ bundle exec rubocop
rubocop-rake extension supports plugin, specify `plugins: rubocop-rake` instead of `require: rubocop-rake` in /Users/masutaka/src/github.com/masutaka/circleci-bundle-update-pr/.rubocop.yml.
For more information, see https://docs.rubocop.org/rubocop/plugin_migration_guide.html.
rubocop-rspec extension supports plugin, specify `plugins: rubocop-rspec` instead of `require: rubocop-rspec` in /Users/masutaka/src/github.com/masutaka/circleci-bundle-update-pr/.rubocop.yml.
For more information, see https://docs.rubocop.org/rubocop/plugin_migration_guide.html.
Inspecting 10 files
..........
10 files inspected, no offenses detected
```
> Fix rubocop warnings

- Gemfile.lock
> bundle update at 2025-05-01 19:11:05 JST

- Gemfile.lock
> bundle update at 2025-06-01 19:11:04 JST
